# Generated by Django 4.2.6 on 2023-12-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('name', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Man'), ('F', 'Female')], max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
